

DEFAULT_RESIZE_RATE = 0.01
LINE_HEIGHT_PERCENT = 1/50
LINE_WIDTH_PERCENT = 2/5
WHITE_THRESHOLD = 100
CROP_PORTION_RATE = 0.8
BOOKSHELF_DIVIDER_RATE = 0.4
CONFIDENCE_THRESHOLD = 50
VERTICAL_CROP_NUM = 2


OVERLAP_PERCENT = 5
X_DISTANCE_THRESHOLD = 0.3
Y_DISTANCE_THRESHOLD = 6
DEBUG = False
recall_threshold = 80
precision_threshold = 80


#%%
